#!/usr/bin/env python3
"""Regenerate UNSAFE.md: the inventory of every `unsafe` block and `unsafe fn` in src/.

Each entry records where it is, what it is, the enclosing function, and the first
line of its `// SAFETY:` justification or `# Safety` contract. CI runs this with
--check and fails if the committed UNSAFE.md is stale, so the inventory cannot drift
from the code (hardening gate H-16).

    python tools/gen_unsafe_inventory.py            # rewrite UNSAFE.md
    python tools/gen_unsafe_inventory.py --check    # exit 1 if stale
"""
import collections
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
AUDITED = "2026-10-04"

FN_RE = re.compile(r'^\s*(?:pub(?:\([^)]*\))?\s+)?(?:const\s+)?(unsafe\s+)?fn\s+(\w+)')
BLOCK_RE = re.compile(r'\bunsafe\s*\{')
UFN_RE = re.compile(r'^\s*(?:pub(?:\([^)]*\))?\s+)?unsafe\s+fn\s+(\w+)')


def first_sentence(lines):
    text = ' '.join(l.strip().lstrip('/').strip() for l in lines)
    text = re.sub(r'^(SAFETY:|# Safety)\s*', '', text).strip()
    m = re.match(r'(.{0,150}?[.;])(\s|$)', text)
    return (m.group(1) if m else text[:150]).replace('|', '\\|')


def scan(path):
    rows = []
    lines = path.read_text(encoding='utf-8').splitlines()
    cur_fn = '-'
    for i, line in enumerate(lines):
        m = FN_RE.match(line)
        if m:
            cur_fn = m.group(2)
        code = line.split('//', 1)[0]
        um = UFN_RE.match(code)
        if um:
            # `# Safety` section of the doc comment above
            j = i - 1
            while j >= 0 and (lines[j].strip().startswith(('#[', '///'))):
                j -= 1
            doc = lines[j + 1:i]
            k = next((n for n, l in enumerate(doc) if '# Safety' in l), None)
            body = [l for l in doc[k + 1:] if l.strip() not in ('///',) and not l.strip().startswith('#[')][:3] if k is not None else []
            rows.append((i + 1, 'unsafe fn', um.group(1), first_sentence(body) if body else 'MISSING # Safety'))
        elif BLOCK_RE.search(code):
            j = i - 1
            while j >= 0 and lines[j].strip().startswith(('//', '#[')):
                j -= 1
            above = [l for l in lines[j + 1:i] if l.strip().startswith('//')]
            s = next((n for n, l in enumerate(above) if 'SAFETY' in l), None)
            # `let x = unsafe {` on the line after its comment, or same-line comment
            just = first_sentence(above[s:s + 3]) if s is not None else (
                'MISSING SAFETY' if 'SAFETY' not in line else first_sentence([line.split('//', 1)[1]]))
            rows.append((i + 1, 'unsafe block', cur_fn, just))
    return rows


def render():
    by_file = collections.OrderedDict()
    for p in sorted((ROOT / 'src').rglob('*.rs')):
        rows = scan(p)
        if rows:
            by_file[p.relative_to(ROOT).as_posix()] = rows
    n_fn = sum(1 for r in by_file.values() for x in r if x[1] == 'unsafe fn')
    n_blk = sum(1 for r in by_file.values() for x in r if x[1] == 'unsafe block')
    out = [
        '# Unsafe code inventory',
        '',
        '<!-- Generated by tools/gen_unsafe_inventory.py - do not edit by hand. -->',
        '',
        f'Every `unsafe` item in `src/`: **{n_fn} `unsafe fn`** and **{n_blk} `unsafe` blocks**, '
        f'all audited {AUDITED}.',
        '',
        'All of it is in SIMD kernels (`#[target_feature]` AVX/AVX2/FMA/SSE on x86, NEON on aarch64) '
        'and their dispatch sites. The entropy coder, packet parsing, and every other '
        'untrusted-input stage are entirely safe Rust. Policy:',
        '',
        '- every `unsafe fn` documents its contract in a `# Safety` section (required CPU features, '
        'slice-length requirements);',
        '- every `unsafe` block carries a `// SAFETY:` comment proving that contract at that site '
        '(enforced: `clippy::undocumented_unsafe_blocks = "deny"`);',
        '- every safe function that reaches a kernel enforces the kernel\'s length contract with an '
        '`assert!` or a checked slice, so misuse panics instead of reading out of bounds;',
        '- each kernel has a scalar twin and a `*_matches_scalar` oracle test that runs on x86_64 '
        'and, under qemu, aarch64 (`RUSTY_OPUS_ISA=scalar` reaches the twins on both).',
        '',
        'Columns: location, kind, enclosing function, and the first line of the justification.',
        '',
    ]
    for f, rows in by_file.items():
        out.append(f'## `{f}` ({len(rows)})')
        out.append('')
        out.append('| Line | Kind | Function | Justification (first line) |')
        out.append('|---:|---|---|---|')
        for ln, kind, fn, just in rows:
            out.append(f'| {ln} | {kind} | `{fn}` | {just} |')
        out.append('')
    return '\n'.join(out) + '\n'


if __name__ == '__main__':
    text = render()
    target = ROOT / 'UNSAFE.md'
    if '--check' in sys.argv:
        if not target.exists() or target.read_text(encoding='utf-8') != text:
            print('UNSAFE.md is stale: run python tools/gen_unsafe_inventory.py', file=sys.stderr)
            sys.exit(1)
        print('UNSAFE.md is current')
    else:
        target.write_text(text, encoding='utf-8', newline='\n')
        missing = text.count('MISSING')
        print(f'wrote UNSAFE.md ({missing} entries missing a justification)')
        sys.exit(1 if missing else 0)
